# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: app_user_registration }

    bip_manager:
         class: AppBundle\Manager\BIPManager
         arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"

    current_site_listener:
        class: AppBundle\EventListener\CurrentBIPListener
        arguments:
            - "@bip_manager"
            - "@doctrine.orm.entity_manager"
            - "%base_host%"
            - "@router"
        tags:
            -
                name: kernel.event_listener
                method: onKernelRequest
                event: kernel.request